# Generated by Django 2.0.2 on 2018-07-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180730_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='votes_total',
        ),
    ]
